### PR TITLE
Feature/stabilize community modules

### PR DESCRIPTION
**Pull request by ismaelTartola**
## Related to Issue
None at this time.

## Description
This is a initial PR that contains the integration of the modules with the Upendo Generator architecture. Main references have been set to use Nuget packages. And the modules build and packaging processes is also integrated to the Upendo Generator build scripts.  

## How Has This Been Tested?
It have been tested in my development environment to build against the scope off DNN version 9.9.0

## Types of changes
- Integration of CommunityMetrics module to Upendo Generator architecture. This change include the module build and package processes.
- Integration of Groups module to Upendo Generator architecture. This change include the module build and package processes.
- Integration of Partners module to Upendo Generator architecture. This change include the module build and package processes.
- Integration of Personalization module to Upendo Generator architecture. This change include the module build and package processes.
- Integration of Showcase module to Upendo Generator architecture. This change include the module build and package processes.
- Change of all the module references to use Nuget packages. The only remaining references being loaded form .dll files are FiftyOne.Fundation, Telerik.Web.UI and WebMatrix.Data.

## Checklist:
- [ X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by ismaelTartola** [comment]
@WillStrohl DO NOT MERGE this PR yet. There are some changes I need to make.

**Comment by WillStrohl** [comment]
@ismaelTartola Okay.  I'll wait for you to let me know.

**Comment by ismaelTartola** [comment]
@WillStrohl I completed the changes. Please proceed to review the PR. Regards.

**Review by WillStrohl — APPROVED** [review]
Approving the initial commit.

**Pull request merged**
